version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  medusa:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:supersecret@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      HOST: 0.0.0.0
      PORT: 9000
    command: >
      sh -c "
      until pg_isready -h postgres -p 5432 -U postgres;
      do echo waiting for db; sleep 2; done;
      yarn medusa db:migrate &&
      yarn start
      "

volumes:
  pgdata:
