version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1111"
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  medusa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:1111@postgres:5432/postgres
        DATABASE_EXTRA: '{"ssl":{"rejectUnauthorized":false}}'
        REDIS_URL: redis://redis:6379
        JWT_SECRET: supersecret
        COOKIE_SECRET: supersecret
        MEDUSA_ADMIN_ONBOARDING_TYPE: nextjs
        MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY: aitronics-storefront
        STORE_CORS: https://aitronics.in
        ADMIN_CORS: https://adm.aitronics.in
        AUTH_CORS: https://aitronics.in,https://adm.aitronics.in
        PORT: "9000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      MEDUSA_ADMIN_ONBOARDING_TYPE: nextjs
      MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY: aitronics-storefront

      STORE_CORS: https://aitronics.in
      ADMIN_CORS: https://adm.aitronics.in
      AUTH_CORS: https://aitronics.in,https://adm.aitronics.in

      PORT: "9000"
      HOST: 0.0.0.0

      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret

      DATABASE_URL: postgresql://postgres:1111@postgres:5432/postgres
      DATABASE_EXTRA: '{"ssl":{"rejectUnauthorized":false}}'
    ports:
      - "9000:9000"
    command: >
      sh -c "
      until pg_isready -h postgres -p 5432 -U postgres;
      do echo waiting for db; sleep 2; done;
      yarn medusa db:migrate &&
      yarn start
      "

volumes:
  pgdata:
